routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\EpisodeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class, 'home'])->name('homepage');
Route::get('/danh-muc/{slug}', [IndexController::class, 'category'])->name('category');
Route::get('the-loai/{slug}', [IndexController::class, 'genre'])->name('genre');
Route::get('/quoc-gia/{slug}', [IndexController::class, 'country'])->name('country');
Route::get('/phim/{slug}', [IndexController::class, 'movie'])->name('movie');
Route::get('/xem-phim/{slug}/{tap}', [IndexController::class, 'watch'])->name('watch');
Route::get('/so-tap', [IndexController::class, 'so_tap'])->name('so-tap');

Route::get('/nam/{year}', [IndexController::class, 'year']);

Route::get('/tag/{tag}', [IndexController::class, 'tag']);

Route::get('/tim-kiem', [IndexController::class, 'timkiem'])->name('tim-kiem');



Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('category', CategoryController::class);
Route::post('resorting', [CategoryController::class,'resorting'])->name('resorting');
Route::resource('genre', GenreController::class);
Route::resource('country', CountryController::class);
Route::resource('episode', EpisodeController::class);
Route::resource('movie', MovieController::class);

Route::get('select-movie', [EpisodeController::class,'select_movie'])->name('select-movie');



Route::get('/update-year-phim', [MovieController::class, 'update_year']);
Route::get('/update-season-phim', [MovieController::class, 'update_season']);

Route::get('/update-topview-phim', [MovieController::class, 'update_topview']);

Route::get('/filter-topview-phim', [MovieController::class, 'filter_topview']);

Route::get('/filter-topview-default', [MovieController::class, 'filter_topview_default']);

app/Models/Episode.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Episode extends Model
{
    public $timestamps = false;
    use HasFactory;

    public function movie(){
        return $this->belongsTo(Movie::class,'movie_id');
    }

}

app/Http/Controllers/EpisodeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Movie;
use App\Models\Episode;
use Carbon\Carbon;

class EpisodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list_episode = Episode::with('movie')->orderBy('movie_id','DESC')->get();
        // return response()->json($list_episode);
        return view('admincp.episode.index', compact('list_episode'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $list_movie = Movie::orderBy('id','DESC')->pluck('title','id','sotap');
        return view('admincp.episode.form', compact('list_movie'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $ep = new Episode();
        $ep->movie_id = $data['movie_id'];
        $ep->linkphim = $data['link'];
        $ep->episode = $data['episode'];
        $ep->created_at =  Carbon::now('Asia/Ho_Chi_Minh');
        $ep->updated_at =  Carbon::now('Asia/Ho_Chi_Minh');
        $ep->save();
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $episode = Episode::find($id);
        $list_movie = Movie::orderBy('id','DESC')->pluck('title','id','sotap');
        return view('admincp.episode.form', compact('episode','list_movie'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $ep = Episode::find($id);
        $ep->movie_id = $data['movie_id'];
        $ep->linkphim = $data['link'];
        $ep->episode = $data['episode'];
        $ep->updated_at =  Carbon::now('Asia/Ho_Chi_Minh');
        $ep->save();
        return redirect()->to('episode');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $episode = Episode::find($id);
        $episode->delete();
    
        return redirect()->back();
    }

    public function select_movie(){
        $id = $_GET['id'];
        $movie = Movie::find($id);
        
        $output = '<option>---Chọn tập phim---</option>';

        if($movie->thuocphim == 'phimbo'){
            for($i =1; $i<= $movie->sotap; $i++){
                $output.= '<option value = "'.$i.'"> '.$i.'</option>';
            }
        }
        else{
            $output.= '<option value = "HD"> HD </option>
                    <option value = "FullHD"> FullHD </option>
                    <option value = "Cam"> Cam </option>
                    <option value = "HDCam"> HDCam </option> ';
        }
        
        echo $output;
    }
}

resources/views/admincp/episode/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
              <a href="{{route('episode.index')}}" class="btn btn-primary">Liệt Kê danh sách Tập phim</a>
                <div class="card-header">Quản lý tập phim</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if(!isset($episode))
                        {!! Form::open(['route'=>'episode.store','method'=>'POST','enctype'=>'multipart/form-data']) !!}
                    @else
                        {!! Form::open(['route'=>['episode.update',$episode->id],'method'=>'PUT','enctype'=>'multipart/form-data']) !!}
                    @endif

                    <div class="form-group">
                        {!! Form::label('movie', 'Chọn Phim', []) !!}
                        {!! Form::select('movie_id',['0'=>'Chọn Phim',''=>$list_movie], isset($episode) ? $episode->movie_id : '', ['class'=>'form-control select-movie']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label('link', 'Link phim', []) !!}
                        {!! Form::text('link', isset($episode) ? $episode->linkphim : '', ['class'=>'form-control','placeholder'=>'...','id'=>'linkphim']) !!}
                    </div>

                    @if(isset($episode))
                        <div class="form-group">
                            {!! Form::label('episode', 'Tập Phim', []) !!}
                            {!! Form::text('episode', isset($episode) ? $episode->episode : '', ['class'=>'form-control','placeholder'=>'...',
                            isset($episode) ? 'readonly': '']) !!}
                       
                        </div>
                    @else
                        <div class="form-group">
                            {!! Form::label('episode', 'Tập Phim', []) !!}
                            <select name="episode" class="form-control" id="show_movie"></select>
                        </div>
                    @endif

                        
                        @if(!isset($episode))
                            {!! Form::submit('Thêm tập phim', ['class'=>'btn btn-success']) !!}
                        @else
                            {!! Form::submit('Cập nhật tập phim', ['class'=>'btn btn-success']) !!}
                        @endif
                    {!! Form::close() !!}
                </div>

            </div>
            
        </div>
    </div>
</div>

@endsection

resources/views/admincp/episode/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <a href="{{route('episode.create')}}" style="margin-bottom: 20px;margin-top: 20px; " class="btn btn-primary">Thêm Phim</a>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Tên Phim</th>
                  <th scope="col">Hình ảnh phim</th>
                  <th scope="col">Tập phim</th>
                  <th scope="col">Link phim</th>
                  <th scope="col">Quản lý</th>
                </tr>
              </thead>
              <tbody >
                @foreach($list_episode as $key => $episode)
                  {{-- @foreach($episode as $key1 => $mov) --}}
                  <tr>
                    <th scope="row">{{$key}}</th>
                    <td>{{$episode->movie->title}}</td>
                    <td><img width="100" src="{{asset('uploads/movie/'.$episode->movie->image)}}"></td>
                    <td>{{$episode->episode}}</td>
                    <td style="width:10%">{!!$episode->linkphim!!}</td>
                    <td>
                        {!! Form::open(['method'=>'DELETE','route'=>['episode.destroy',$episode->id],'onsubmit'=>'return confirm("Bạn có chắc muốn xóa?")']) !!}
                          {!! Form::submit('Xóa', ['class'=>'btn btn-danger']) !!}
                        {!! Form::close() !!}
                        <a href="{{route('episode.edit',$episode->id)}}" class="btn btn-warning">Sửa</a>
                    </td>
                  </tr>
                  {{-- @endforeach --}}
                @endforeach
              </tbody>
            </table>
        </div>
    </div>
</div>
@endsection