routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\EpisodeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class, 'home'])->name('homepage');
Route::get('/danh-muc/{slug}', [IndexController::class, 'category'])->name('category');
Route::get('the-loai/{slug}', [IndexController::class, 'genre'])->name('genre');
Route::get('/quoc-gia/{slug}', [IndexController::class, 'country'])->name('country');
Route::get('/phim/{slug}', [IndexController::class, 'movie'])->name('movie');
Route::get('/xem-phim/{slug}/{tap}', [IndexController::class, 'watch'])->name('watch');
Route::get('/so-tap', [IndexController::class, 'so_tap'])->name('so-tap');

Route::get('/nam/{year}', [IndexController::class, 'year']);

Route::get('/tag/{tag}', [IndexController::class, 'tag']);

Route::get('/tim-kiem', [IndexController::class, 'timkiem'])->name('tim-kiem');



Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('category', CategoryController::class);
Route::post('resorting', [CategoryController::class,'resorting'])->name('resorting');
Route::resource('genre', GenreController::class);
Route::resource('country', CountryController::class);
Route::resource('episode', EpisodeController::class);
Route::resource('movie', MovieController::class);

Route::get('select-movie', [EpisodeController::class,'select_movie'])->name('select-movie');



Route::get('/update-year-phim', [MovieController::class, 'update_year']);
Route::get('/update-season-phim', [MovieController::class, 'update_season']);

Route::get('/update-topview-phim', [MovieController::class, 'update_topview']);

Route::get('/filter-topview-phim', [MovieController::class, 'filter_topview']);

Route::get('/filter-topview-default', [MovieController::class, 'filter_topview_default']);

app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
	public $timestamps = false;
    use HasFactory;
    public function category(){
    	return $this->belongsTo(Category::class,'category_id');
    }
    public function country(){
    	return $this->belongsTo(Country::class,'country_id');
    }
    public function genre(){
    	return $this->belongsTo(Genre::class,'genre_id');
    }

    public function movie_genre(){
        return $this->belongsToMany(Genre::class, 'movie_genre','movie_id', 'genre_id');
    }

    public function episode()
    {
            return $this->hasMany(Episode::class);
    }
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Movie;
use App\Models\Category;
use App\Models\Genre;
use App\Models\Country;
use App\Models\Movie_Genre;
use App\Models\Episode;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

class MovieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list = Movie::with('category','movie_genre','genre','country')->orderBy('id','DESC')->get();
       
        $path = public_path()."/json_file/";
        if(!is_dir($path)){
            mkdir($path, 0777, true);
        }
        File::put($path.'movies.json', json_encode($list));
        return view('admincp.movie.index', compact('list'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::pluck('title','id');
        $genre = Genre::pluck('title','id');
        $list_genre = Genre::all();
        $country = Country::pluck('title','id');
        return view('admincp.movie.form', compact('category','genre','country','list_genre'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $movie = new Movie();
        $movie->title = $data['title'];
        $movie->sotap = $data['sotap'];
        $movie->thoiluong = $data['thoiluong'];
        $movie->slug = $data['slug'];
        $movie->year = $data['year'];
        $movie->trailer = $data['trailer'];
        $movie->season = $data['season'];
        $movie->tags = $data['tags'];
        $movie->name_eng = $data['name_eng'];
        $movie->phim_hot = $data['phim_hot'];
        $movie->phude = $data['phude'];
        $movie->resolution = $data['resolution'];
        $movie->description = $data['description'];
        $movie->status = $data['status'];
        $movie->category_id = $data['category_id'];
        $movie->thuocphim = $data['thuocphim'];
        $movie->country_id = $data['country_id'];
        $movie->ngaytao = Carbon::now('Asia/Ho_Chi_Minh');
        $movie->ngaycapnhap = Carbon::now('Asia/Ho_Chi_Minh');
        $movie->country_id = $data['country_id'];

        foreach ($data['genre'] as $key => $gen){
            $movie->genre_id = $gen[0];
        }

       

        $get_image = $request->file('image');

        if($get_image){

            $get_name_image = $get_image->getClientOriginalName();
            $name_image = current(explode('.',$get_name_image));
            $new_image = $name_image.rand(0,9999).'.'.$get_image->getClientOriginalExtension();
            $get_image->move('uploads/movie/',$new_image);
            $movie->image = $new_image;
        }
        $movie->save();
        //Thêm nhiều thể loại cho phim
        $movie->movie_genre()->sync($data['genre']);
        return redirect()->route('movie.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::pluck('title','id');
        $genre = Genre::pluck('title','id');
        $country = Country::pluck('title','id');
        $list_genre = Genre::all();
        $movie =  Movie::find($id);
        $movie_genre = $movie->movie_genre;
    
        return view('admincp.movie.form', compact('category','genre','country','movie','list_genre','movie_genre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $movie = Movie::find($id);
        $movie->title = $data['title'];
        $movie->sotap = $data['sotap'];
        $movie->tags = $data['tags'];
        $movie->thoiluong = $data['thoiluong'];
        $movie->slug = $data['slug'];
        $movie->trailer = $data['trailer'];
        $movie->year = $data['year'];
        $movie->season = $data['season'];
        $movie->name_eng = $data['name_eng'];
        $movie->phim_hot = $data['phim_hot'];
        $movie->phude = $data['phude'];
        $movie->resolution = $data['resolution'];
        $movie->description = $data['description'];
        $movie->status = $data['status'];
        $movie->category_id = $data['category_id'];
        $movie->thuocphim = $data['thuocphim'];
        $movie->country_id = $data['country_id'];
        $movie->ngaycapnhap = Carbon::now('Asia/Ho_Chi_Minh');
        $get_image = $request->file('image');

        foreach ($data['genre'] as $key => $gen){
            $movie->genre_id = $gen[0];
        }

        if($get_image){
            if(file_exists('uploads/movie/'.$movie->image)){
                unlink('uploads/movie/'.$movie->image);
            }else{
            
            $get_name_image = $get_image->getClientOriginalName();
            $name_image = current(explode('.',$get_name_image));
            $new_image = $name_image.rand(0,9999).'.'.$get_image->getClientOriginalExtension();
            $get_image->move('uploads/movie/',$new_image);
            $movie->image = $new_image;
            }
        }
        $movie->save();
        $movie->movie_genre()->sync($data['genre']);
        return redirect()->route('movie.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $movie = Movie::find($id);
        //xóa ảnh
        if(file_exists('uploads/movie/'.$movie->image)){
            unlink('uploads/movie/'.$movie->image);
        }
        //xóa thể loại
        Movie_Genre::whereIN('movie_id',[$movie->id])->delete();
        //Xóa tập phim khi xóa phim
        Episode::whereIN('movie_id',[$movie->id])->delete();
        //Xóa phim 
        $movie->delete();
        return redirect()->back();
    }

    public function update_year(Request $request){
        $data = $request->all();
        $movie = Movie::find($data['id_phim']);
        $movie->year = $data['year'];
        $movie->save();
    }

    public function update_season(Request $request){
        $data = $request->all();
        $movie = Movie::find($data['id_phim']);
        $movie->season = $data['season'];
        $movie->save();
    }

    public function update_topview(Request $request){
        $data = $request->all();
        $movie = Movie::find($data['id_phim']);
        $movie->topview = $data['topview'];
        $movie->save();
    }

    public function filter_topview(Request $request){
        $data = $request->all();
        $movie = Movie::where('topview', $data['value'])->orderBy('ngaycapnhap', 'DESC')->take(20)->get();
        $output = '';
        foreach($movie as $key => $mov){
            if($mov->resolution == 0){
                $text = 'HD';
            }
            elseif($mov->resolution == 1){
                $text = 'SD';
            }
            elseif($mov->resolution == 2){
                $text = 'HDCam';
            }
            elseif($mov->resolution == 3){
                $text = 'Cam';
            }
            elseif($mov->resolution == 4){
                $text = 'FullHD';
            }
            else{
                $text = 'Trailer';
            }
            

            $output .= '<div class="item ">
                            <a href="'.url('phim/'.$mov->slug).'"title= " '.$mov->title.'">
                                <div class="item-link">
                                    <img src="'.url('uploads/movie/'.$mov->image).'" class="lazy post-thumb" alt=" '.$mov->title.'" title=" '.$mov->title.'" />
                                    <span class="is_trailer">
                                    '.$text.'
                                    </span>
                                </div>
                                <p class="title"> '.$mov->title.'</p>
                            </a>
                            <div class="viewsCount" style="color: #9d9d9d;">3.2K lượt xem</div>
                            <div style="float: left;">
                                <span class="user-rate-image post-large-rate stars-large-vang" style="display: block;/* width: 100%; */">
                                <span style="width: 0%"></span>
                                </span>
                            </div>
                        </div>';

        }
        echo $output;  
    }

    public function filter_topview_default(Request $request){
        $data = $request->all();
        $movie = Movie::where('topview', 0)->orderBy('ngaycapnhap', 'DESC')->take(20)->get();
        $output = '';
        foreach($movie as $key => $mov){
            if($mov->resolution == 0){
                $text = 'HD';
            }
            elseif($mov->resolution == 1){
                $text = 'SD';
            }
            elseif($mov->resolution == 2){
                $text = 'HDCam';
            }
            else{
                $text = 'Cam';
            }

            $output .= '<div class="item ">
                            <a href="'.url('phim/'.$mov->slug).'"title= " '.$mov->title.'">
                                <div class="item-link">
                                    <img src="'.url('uploads/movie/'.$mov->image).'" class="lazy post-thumb" alt=" '.$mov->title.'" title=" '.$mov->title.'" />

resources/views/admincp/movie/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
              <a href="{{route('movie.index')}}" class="btn btn-primary">Liệt Kê Danh Sách Phim</a>
                <div class="card-header">Quản Lý Phim</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if(!isset($movie))
                        {!! Form::open(['route'=>'movie.store','method'=>'POST','enctype'=>'multipart/form-data']) !!}
                    @else
                        {!! Form::open(['route'=>['movie.update',$movie->id],'method'=>'PUT','enctype'=>'multipart/form-data']) !!}
                    @endif
                        <div class="form-group">
                            {!! Form::label('title', 'Tên phim', []) !!}
                            {!! Form::text('title', isset($movie) ? $movie->title : '', ['class'=>'form-control','placeholder'=>'...','id'=>'slug','onkeyup'=>'ChangeToSlug()']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('tên tiếng anh', 'Tên tiếng anh', []) !!}
                            {!! Form::text('name_eng', isset($movie) ? $movie->name_eng : '', ['class'=>'form-control','placeholder'=>'...']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('slug', 'Đường dẫn', []) !!}
                            {!! Form::text('slug', isset($movie) ? $movie->slug : '', ['class'=>'form-control','placeholder'=>'...','id'=>'convert_slug']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('sotap', 'Số Tập', []) !!}
                            {!! Form::text('sotap', isset($movie) ? $movie->sotap : '', ['class'=>'form-control','placeholder'=>'...']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('trailer', 'Trailer', []) !!}
                            {!! Form::text('trailer', isset($movie->trailer) ? $movie->trailer : '', ['class'=>'form-control','placeholder'=>'...']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('thoiluong', 'Thời Lượng', []) !!}
                            {!! Form::text('thoiluong', isset($movie) ? $movie->thoiluong : '', ['class'=>'form-control','placeholder'=>'...','id'=>'thoiluong']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('description', 'Mô tả phim', []) !!}
                            {!! Form::textarea('description', isset($movie) ? $movie->description : '', ['style'=>'resize:none', 'class'=>'form-control','placeholder'=>'...','id'=>'description']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('tags', 'Tags phim', []) !!}
                            {!! Form::textarea('tags', isset($movie) ? $movie->tags : '', ['style'=>'resize:none', 'class'=>'form-control','placeholder'=>'...']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('status', 'Trạng thái', []) !!}
                            {!! Form::select('status', ['1'=>'Hiển thị','0'=>'Không hiển thị'], isset($movie) ? $movie->status : '', ['class'=>'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('resolution', 'Định dạng', []) !!}
                            {!! Form::select('resolution', ['0'=>'HD','1'=>'SD', '2'=>'HDcam', '3'=>'cam', '4'=>'FullHD', '5'=>'Trailer'], isset($movie) ? $movie->resolution : '', ['class'=>'form-control']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('phude', 'Phụ đề', []) !!}
                            {!! Form::select('phude', ['0'=>'Phụ đề','1'=>'Thuyết minh'], isset($movie) ? $movie->phude : '', ['class'=>'form-control']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('Năm', 'Năm', []) !!}
                            {!! Form::selectYear('year', 2000, 2022 ,isset($movie->year) ? $movie->year: ' ', ['class'=>'form-control'] ) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('Category', 'Danh mục', []) !!}
                            {!! Form::select('category_id', $category, isset($movie) ? $movie->category_id : '', ['class'=>'form-control']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('thuocphim', 'Thuộc loại phim', []) !!}
                            {!! Form::select('thuocphim',['phimle'=>'Phim lẻ','phimbo'=>'Phim bộ'], isset($movie) ? $movie->thuocphim : '', ['class'=>'form-control']) !!}
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('Country', 'Quốc gia', []) !!}
                            {!! Form::select('country_id', $country, isset($movie) ? $movie->country_id : '', ['class'=>'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Genre', 'Thể loại', []) !!}<br/>
                            @foreach ($list_genre as $key => $gen)
                                @if(isset($movie))
                            {!! Form::checkbox('genre[]', $gen->id, isset($movie_genre) && $movie_genre->contains($gen->id) ? true : false )!!}
                                @else
                            {!! Form::checkbox('genre[]', $gen->id, '')!!}
                                @endif
                            {!! Form::label('genre', $gen->title) !!}
                                
                            @endforeach
                            {{-- {!! Form::select('genre_id', $genre, isset($movie) ? $movie->genre_id : '', ['class'=>'form-control']) !!} --}}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Hot', 'Phim hot', []) !!}
                            {!! Form::select('phim_hot', ['1'=>'Có','0'=>'Không'], isset($movie) ? $movie->phim_hot : '', ['class'=>'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Season', 'Season', []) !!}
                            {!! Form::selectRange('season', 0, 20 ,isset($cate->season) ? $cate->season: ' ', ['class'=>'form-control'] ) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Image', 'Hình ảnh', []) !!}
                            {!! Form::file('image', ['class'=>'form-control-file']) !!}
                            @if(isset($movie))
                              <img width="150" src="{{asset('uploads/movie/'.$movie->image)}}">
                            @endif
                        </div>
                        @if(!isset($movie))
                            {!! Form::submit('Thêm Phim', ['class'=>'btn btn-success']) !!}
                        @else
                            {!! Form::submit('Cập Nhật Phim', ['class'=>'btn btn-success']) !!}
                        @endif
                    {!! Form::close() !!}
                </div>
            </div>
            
        </div>
    </div>
</div>
@endsection

resources/views/admincp/movie/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <a href="{{route('movie.create')}}" style="margin-bottom: 20px;margin-top: 20px; " class="btn btn-primary">Thêm Phim</a>
            <table class="table" id="tablephim">
              <thead>
                <tr>
                  <th scope="col">STT</th>
                  <th scope="col">Tên phim</th>
                  <th scope="col">Tags</th>
                  <th scope="col">Hình ảnh</th>
                  <th scope="col">Số tập</th>
                  <th scope="col">Phim hot</th>
                  <th scope="col">Định dạng</th>
                  <th scope="col">Phụ đề</th>
                  <!-- <th scope="col">Mô tả</th> -->
                  <th scope="col">Đường dẫn</th>
                  <th scope="col">Thời Lượng</th>
                  <th scope="col">Trạng thái</th>
                  <th scope="col">Danh mục</th>
                  <th scope="col">Thuộc phim</th>
                  <th scope="col">Thể loại</th>
                  <th scope="col">Quốc gia</th>
                  <th scope="col">Ngày Tạo</th>
                  <th scope="col">Ngày Cập Nhập</th>
                  <th scope="col">Năm</th>
                  <th scope="col">Season</th>
                  <th scope="col">Top Views</th>
                  <th scope="col">Quản lý</th>
                </tr>
              </thead>
              <tbody>
                @foreach($list as $key => $cate)
                <tr>
                  <th scope="row">{{$key}}</th>
                  <td>{{$cate->title}}</td>
                  <td>{{substr($cate->tags, 0, 50)}}</td>
                  <td><img width="100" src="{{asset('uploads/movie/'.$cate->image)}}"></td>
                  <td>{{$cate->sotap}}</td>
                  <td>
                    @if($cate->phim_hot==0)
                        Không
                    @else
                        Có
                    @endif
                    
                  </td>
                  <td>
                    @if($cate->resolution==0)
                        HD
                    @elseif($cate->resolution==1)
                        SD
                    @elseif($cate->resolution==2)
                        HDcam
                    @elseif($cate->resolution==3)
                        cam
                    @elseif($cate->resolution==4)
                        FullHD
                    @else
                        Trailer
                    @endif
                  </td>
                  <td>
                    @if($cate->phude ==0)
                        Phụ đề
                    @else
                        Thuyết minh
                    @endif
                  </td>
                  {{-- <!-- <td>{{$cate->description}}</td> --> --}}
                  <td>{{$cate->slug}}</td>
                  <td>{{$cate->thoiluong}}</td>
                  <td>
                    @if($cate->status)
                        Hiển thị
                    @else
                        Không hiển thị
                    @endif
                  </td>
                  <td>{{$cate->category->title}}</td>
                  <td>
                    @if ($cate->thuocphim == 'phimbo')
                      Phim bộ  
                    @else
                        Phim lẻ
                    @endif
                  </td>

                  <td>
                  @foreach($cate->movie_genre as $gen)
                  <span  class="badge badge-dark">{{$gen->title}}</span>
                     
                  @endforeach

                </td>
                  <td>{{$cate->country->title}}</td>
                  <td>{{$cate->ngaytao}}</td>
                  <td>{{$cate->ngaycapnhap}}</td>
                  <td>
                    <form method="POST">
                      @csrf
                      {!! Form::selectYear('year', 2000, 2022, isset($cate->year) ? $cate->year: ' ', ['class'=>'select_year', 'id'=>$cate->id]) !!}
                    </form>
                   </td>

                  <td>
                    <form method="POST">
                      @csrf
                      {!! Form::selectRange('season', 0, 20 ,isset($cate->season) ? $cate->season: ' ', ['class'=>'select_season', 'id'=>$cate->id]) !!}
                    </form>
                   </td>

                  <td>
                    {!! Form::select('topview', ['0'=>'Ngày','1'=>'Tuần', '2'=>'Tháng'], isset($cate->topview) ? $cate->topview : '', ['class'=>'select-topview', 'id'=>$cate->id]) !!}
                  </td>
                  <td>
                      {!! Form::open(['method'=>'DELETE','route'=>['movie.destroy',$cate->id],'onsubmit'=>'return confirm("Bạn có chắc muốn xóa?")']) !!}
                        {!! Form::submit('Xóa', ['class'=>'btn btn-danger']) !!}
                      {!! Form::close() !!}
                      <a href="{{route('movie.edit',$cate->id)}}" class="btn btn-warning">Sửa</a>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
        </div>
    </div>
</div>
@endsection